---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Code Scan

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Check Code
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          # We will set fetch-depth: 0 to fetch all history for all branches
          # If you hadn't done this, only a single commit would be fetched.
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        # https://github.com/marketplace/actions/super-linter#environment-variables
        env:
          # Change to 'true' to scan all files, 'false' for new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Change to 'master' if your main branch differs
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSS_FILE_NAME: .stylelintrc.json
          LINTER_RULES_PATH: .github/linters
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          PHP_CONFIG_FILE: php.ini
          YAML_CONFIG_FILE: .yaml-lint.yml
          FILTER_REGEX_EXCLUDE: (Releases.*|Screenshots.*)
          # ACTIONS_RUNNER_DEBUG: true
          # CREATE_LOG_FILE: true
          # LOG_FILE: code-linter.log
          # LOG_LEVEL: WARN
          ACTIONS_STEP_DEBUG: true
          IGNORE_GITIGNORED_FILES: true
          SUPPRESS_POSSUM: true
          VALIDATE_CSS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_HTML: true
          # VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PHP: true
          VALIDATE_PHP_BUILTIN: true
          VALIDATE_PHP_PHPCS: true
          # VALIDATE_PHP_PHPSTAN: true
          # VALIDATE_PHP_PSALM: true
          # VALIDATE_SHELL_SHFMT: true
          # VALIDATE_SQL: true
          # VALIDATE_SQLFLUFF: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
